
# ianorth-api/Dockerfile.worker.dev
FROM ultralytics/ultralytics:latest

WORKDIR /app

# Instala as dependências do OpenCV
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY ./ianorth-api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./ianorth-api/app /app/app


CMD ["python", "-u", "-m", "app.worker_dispatcher"]
