services:
  core_system:
    build:  
      context: ./ianorth-api
      dockerfile: Dockerfile.edge 
    container_name: ianorth_backend 
    env_file:
      - ./ianorth-api/.env
    environment:
      - OPENCV_FFMPEG_CAPTURE_OPTIONS=rtsp_transport;tcp
      - TZ=America/Sao_Paulo
    ports:
      - "8036:8898"
    volumes:
      - ./ianorth-api/uploads:/app/uploads
      - ./ianorth-api/models:/app/models
      - ./banco_local:/app/data
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices: [{driver: nvidia, count: all, capabilities: [gpu]}]

  frontend:
    build:
      context: ./ianorth-web
      dockerfile: Dockerfile
    container_name: ianorth-web
    ports:
     - "8026:80"
    depends_on:
     - core_system
    restart: unless-stopped
