#refatorar o compose, serviço unificados 
services:
#API + INferencia + Banco SQLite tudo num lugar só
  core_system:
    build:  
      context: ./ianorth-api
      dockerfile: Dockerfile.edge 
    container_name: ianorth_backend 
    env_file:
      - ./ianorth-api/.env
    ports:
      - "8036:8898"
    volumes:
      - ./ianorth-api/uploads:/app/uploads
      - ./ianorth-api/models:/app/models
      # a linha abaixo garante que o arquivo SQLite fique salvo na máquina host
      # e não se perca se você desligar o container!
      - ./banco_local:/app/data
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices: [{driver: nvidia, count: all, capabilities: [gpu]}]

  frontend:
    build:
      context: ./ianorth-web
      dockerfile: Dockerfile
    container_name: ianorth-frontend
    ports:
     - "8026:80"
    depends_on:
     - core_system
    restart: unless-stopped
